// jadesbrowbeauty_services_component.js

// Define an object for service categories.
// Adding a FACIAL key to account for the facial waxing services.
export const SERVICE_CATEGORIES = {
	BROWS: 'Brows',
	BROWS_LASHES: 'Brows & Lashes',
	FACIAL: 'Facial Waxing',
	BODY: 'Body Waxing',
  };
  
  // Array of service objects representing each service offered.
  // This flat structure is designed for consistency and easier sorting/filtering.
  // Additional properties include image paths, descriptions, durations, popularity, and optional highlight flags.
export default function ServicesList() {
  return [
    // Brow Services
    {
      id: 1,
      name: 'Brow Wax',
      price: 30,
      image: 'BrowShape.png',
      description: 'Precision brow waxing to clean and shape your brows.',
      category: SERVICE_CATEGORIES.BROWS,
      duration: '20 min',
      popularity: 6,
    },
    {
      id: 2,
      name: 'Brow Wax & Tint',
      price: 50,
      image: '/images/brow-wax-tint.png',
      description: 'Combine waxing with a tint for added definition. Includes an add-on tint option.',
      category: SERVICE_CATEGORIES.BROWS,
      duration: '20 min',
      popularity: 7,
    },
    {
      id: 3,
      name: 'Lash Lamination & Tint',
      price: 120,
      image: '/images/lash-lamination-tint.png',
      description: 'Enhance your lashes with lamination and tint for a natural lift.',
      category: SERVICE_CATEGORIES.BROWS_LASHES,
      duration: '1 hr',
      popularity: 8,
    },
    {
      id: 4,
      name: 'Brow Wax & Lamination',
      price: 100,
      image: '/.png',
      description: 'Achieve styled brows with waxing and lamination. Tint option available at $120.',
      category: SERVICE_CATEGORIES.BROWS,
      duration: '45 min',
      popularity: 7,
    },
    {
      id: 5,
      name: 'Brow & Lash Lux',
      price: 140,
      image: '/images/brow-lash-lux.png',
      description: 'A premium treatment combining brow and lash services. Enhanced service with an optional tint upgrade available at $160.',
      category: SERVICE_CATEGORIES.BROWS_LASHES,
      duration: '1 hr',
      popularity: 9,
      highlight: true,
    },
    // Facial Waxing
    {
      id: 6,
      name: 'Full Face Waxing',
      price: 80,
      image: '/images/full-face-waxing.png',
      description: 'Comprehensive waxing covering the entire face for a smooth finish.',
      category: SERVICE_CATEGORIES.FACIAL,
      duration: '30 min',
      popularity: 6,
    },
    {
      id: 7,
      name: 'Half Face Waxing',
      price: 60,
      image: '/images/half-face-waxing.png',
      description: 'Partial facial waxing to remove unwanted hair quickly and efficiently.',
      category: SERVICE_CATEGORIES.FACIAL,
      duration: '20 min',
      popularity: 5,
    },
    {
      id: 8,
      name: 'Nose Waxing',
      price: 15,
      image: '/images/nose-waxing.png',
      description: 'Gentle waxing to remove nasal hair with minimal discomfort.',
      category: SERVICE_CATEGORIES.FACIAL,
      duration: '10 min',
      popularity: 5,
    },
    {
      id: 9,
      name: 'Lip Waxing',
      price: 15,
      image: '/images/lip-waxing.png',
      description: 'Quick and precise waxing for the upper lip for a clean look.',
      category: SERVICE_CATEGORIES.FACIAL,
      duration: '10 min',
      popularity: 5,
    },
    {
      id: 10,
      name: 'Chin Waxing',
      price: 20,
      image: '/images/chin-waxing.png',
      description: 'Effective waxing for the chin area to enhance facial aesthetics.',
      category: SERVICE_CATEGORIES.FACIAL,
      duration: '10 min',
      popularity: 5,
    },
    // Body Waxing
    {
      id: 11,
      name: 'Underarm Waxing',
      price: 30,
      image: '/images/underarm-waxing.png',
      description: 'Smooth and hygienic waxing for the underarm area.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '15 min',
      popularity: 5,
    },
    {
      id: 12,
      name: 'Full Arm Waxing',
      price: 60,
      image: '/images/full-arm-waxing.png',
      description: 'Complete arm waxing to leave your arms smooth and hair-free.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '30 min',
      popularity: 6,
    },
    {
      id: 13,
      name: 'Half Arm Waxing',
      price: 40,
      image: '/images/half-arm-waxing.png',
      description: 'Targeted waxing for either the upper or lower arm areas.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '20 min',
      popularity: 5,
    },
    {
      id: 14,
      name: 'Full Leg Waxing',
      price: 80,
      image: '/images/full-leg-waxing.png',
      description: 'Complete leg waxing for long-lasting smoothness.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '40 min',
      popularity: 7,
    },
    {
      id: 15,
      name: 'Lower Leg Waxing',
      price: 45,
      image: '/images/lower-leg-waxing.png',
      description: 'Focused waxing on the lower leg for a neat finish.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '25 min',
      popularity: 6,
    },
    {
      id: 16,
      name: 'Chest Wax',
      price: 50,
      image: '/images/chest-wax.png',
      description: 'Professional chest waxing for a clean and refined appearance.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '20 min',
      popularity: 6,
    },
    {
      id: 17,
      name: 'Full Back Wax',
      price: 80,
      image: '/images/full-back-wax.png',
      description: 'Comprehensive waxing to achieve a completely hair-free back.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '40 min',
      popularity: 7,
    },
    {
      id: 18,
      name: 'Upper/Lower Wax',
      price: 45,
      image: '/images/upper-lower-wax.png',
      description: 'Combined waxing for both upper and lower sections of the body.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '25 min',
      popularity: 6,
    },
    {
      id: 19,
      name: 'Bikini Line Wax',
      price: 45,
      image: '/images/bikini-line-wax.png',
      description: 'Precision waxing for a well-groomed bikini line.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '15 min',
      popularity: 5,
    },
    {
      id: 20,
      name: 'Brazilian Wax',
      price: 60,
      image: '/images/brazilian-wax.png',
      description: 'Full Brazilian waxing for a complete hair removal solution.',
      category: SERVICE_CATEGORIES.BODY,
      duration: '30 min',
      popularity: 6,
    },
  ];
}